services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: microshop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/postgres-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d microshop" ]
      interval: 5s

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK_RELATIVE: 0.7
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_running" ]
      interval: 10s

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    command: /usr/local/bin/etcd --advertise-client-urls http://etcd:2379 --listen-client-urls http://0.0.0.0:2379
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./infra/minio-init/init.sh:/init.sh
      - ./infra/generated-images/products:/seed/products
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    entrypoint: /bin/sh /init.sh


  auth-service:
    build: ./auth-service-go
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - REDIS_HOST=redis
    depends_on:
      etcd: { condition: service_started }
      redis: { condition: service_healthy }

  backend-service:
    build: ./backend-java
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/microshop
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_REDIS_HOST=redis
      - SPRING_RABBITMQ_HOST=rabbitmq
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      postgres: { condition: service_healthy }
      rabbitmq: { condition: service_healthy }
      redis: { condition: service_healthy }

  order-worker:
    build: ./order-worker-python
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=microshop
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_QUEUE=orders.queue

      - PYTHONUNBUFFERED=1
    depends_on:
      postgres: { condition: service_healthy }
      rabbitmq: { condition: service_healthy }

  frontend:
    build: ./frontend-react


  gateway:
    build: ./nginx-gateway
    ports:
      - "3000:80"
    depends_on:
      - frontend
      - auth-service
      - backend-service

volumes:
  pgdata:
  catalogue_postgres_data:
  etcd_data:
  minio_data: